### ISSUE TITLE
Error during getting some files

### ISSUE THREAD

**Issue by comm1x** [allyshka/pwngitmanager#1]
Cannot download some files and get below error text:

```
# pwngit http://... -c 'get includes/config.php'
Downloading 'includes/config.php' file ...
Traceback (most recent call last):
  File "/usr/local/bin/pwngit", line 41, in <module>
    print(new.exec(c))
  File "/root/tools/pwngitmanager/gitlib.py", line 701, in exec
    self.show(getattr(executor, command)(cmd["args"]))
  File "/root/tools/pwngitmanager/gitlib.py", line 390, in get
    self.__get(file, show)
  File "/root/tools/pwngitmanager/gitlib.py", line 421, in __get
    deflate_data = self.__deflate(data)
  File "/root/tools/pwngitmanager/gitlib.py", line 517, in __deflate
    return zlib.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect header check
```

Place of exception:

```
516     def __deflate(self, data):
517         return zlib.decompress(data)
```

Debugging shows that in successful attempts variable `data` contains binary data. On fail `data` contains plain html-code. For example:

```
b'<!DOCTYPE html>\n<html>\n    <head>\n        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n        <title>\xd0\x9a
...
</script>\n            </body>\n</html>\n'
```

**Comment by allyshka** [comment]
Hello.
I guess problem exists because of web server answers with valid response code (ex.: 200 OK) for non-existent resources instead 404 Not found. Then script continue working and try to decompress plain text data.
I'll add catch for this error with new commit today or tomorrow. 
Thank you for report issue.

**Comment by allyshka** [comment]
Please pull changes. I am added exception cath for failed objects decompression. And also added proxy support.

**Comment by ghost** [comment]
@comm1x how do you debug it ?
